// Code generated by protoc-gen-go. DO NOT EDIT.
// source: traffic/traffic.proto

package traffic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTravelTimeRequest struct {
	Origin               string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTravelTimeRequest) Reset()         { *m = GetTravelTimeRequest{} }
func (m *GetTravelTimeRequest) String() string { return proto.CompactTextString(m) }
func (*GetTravelTimeRequest) ProtoMessage()    {}
func (*GetTravelTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b91e267bbb4bdf8, []int{0}
}

func (m *GetTravelTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTravelTimeRequest.Unmarshal(m, b)
}
func (m *GetTravelTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTravelTimeRequest.Marshal(b, m, deterministic)
}
func (m *GetTravelTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTravelTimeRequest.Merge(m, src)
}
func (m *GetTravelTimeRequest) XXX_Size() int {
	return xxx_messageInfo_GetTravelTimeRequest.Size(m)
}
func (m *GetTravelTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTravelTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTravelTimeRequest proto.InternalMessageInfo

func (m *GetTravelTimeRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *GetTravelTimeRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type GetTravelTimeReply struct {
	TravelTime           *duration.Duration `protobuf:"bytes,1,opt,name=travelTime,proto3" json:"travelTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTravelTimeReply) Reset()         { *m = GetTravelTimeReply{} }
func (m *GetTravelTimeReply) String() string { return proto.CompactTextString(m) }
func (*GetTravelTimeReply) ProtoMessage()    {}
func (*GetTravelTimeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b91e267bbb4bdf8, []int{1}
}

func (m *GetTravelTimeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTravelTimeReply.Unmarshal(m, b)
}
func (m *GetTravelTimeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTravelTimeReply.Marshal(b, m, deterministic)
}
func (m *GetTravelTimeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTravelTimeReply.Merge(m, src)
}
func (m *GetTravelTimeReply) XXX_Size() int {
	return xxx_messageInfo_GetTravelTimeReply.Size(m)
}
func (m *GetTravelTimeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTravelTimeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTravelTimeReply proto.InternalMessageInfo

func (m *GetTravelTimeReply) GetTravelTime() *duration.Duration {
	if m != nil {
		return m.TravelTime
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTravelTimeRequest)(nil), "traffic.GetTravelTimeRequest")
	proto.RegisterType((*GetTravelTimeReply)(nil), "traffic.GetTravelTimeReply")
}

func init() {
	proto.RegisterFile("traffic/traffic.proto", fileDescriptor_9b91e267bbb4bdf8)
}

var fileDescriptor_9b91e267bbb4bdf8 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x9d, 0x87, 0x0d, 0xdf, 0xf0, 0x12, 0x54, 0xe6, 0x44, 0x19, 0x3d, 0x79, 0x4a, 0x58,
	0x3d, 0x88, 0x57, 0x11, 0x3c, 0x89, 0x52, 0x7a, 0x10, 0x6f, 0xe9, 0x9a, 0x76, 0x4f, 0xda, 0xbc,
	0x9a, 0xbe, 0x08, 0xfb, 0xef, 0x85, 0x34, 0x93, 0x39, 0xdc, 0x29, 0xbc, 0xef, 0x3d, 0x7e, 0xfc,
	0xbe, 0xc0, 0x39, 0x3b, 0x5d, 0x55, 0xb8, 0x52, 0xf1, 0x95, 0x9d, 0x23, 0x26, 0x31, 0x89, 0xe3,
	0xfc, 0xa6, 0x26, 0xaa, 0x1b, 0xa3, 0x42, 0x5c, 0xf8, 0x4a, 0x95, 0xde, 0x69, 0x46, 0xb2, 0xc3,
	0x61, 0xf2, 0x06, 0x67, 0xcf, 0x86, 0x73, 0xa7, 0xbf, 0x4d, 0x93, 0x63, 0x6b, 0x32, 0xf3, 0xe5,
	0x4d, 0xcf, 0xe2, 0x02, 0xc6, 0xe4, 0xb0, 0x46, 0x3b, 0x1b, 0x2d, 0x46, 0xb7, 0x27, 0x59, 0x9c,
	0xc4, 0x02, 0xa6, 0xa5, 0xe9, 0x19, 0x6d, 0x80, 0xcc, 0x8e, 0xc3, 0x72, 0x37, 0x4a, 0x5e, 0x41,
	0xec, 0x11, 0xbb, 0x66, 0x23, 0x1e, 0x00, 0xf8, 0x37, 0x0a, 0xcc, 0x69, 0x7a, 0x29, 0x07, 0x39,
	0xb9, 0x95, 0x93, 0x4f, 0x51, 0x2e, 0xdb, 0x39, 0x4e, 0xdf, 0x61, 0x92, 0x0f, 0x6d, 0xc4, 0x0b,
	0x9c, 0xfe, 0x61, 0x8b, 0x6b, 0xb9, 0xed, 0xfd, 0x5f, 0x8b, 0xf9, 0xd5, 0xa1, 0x75, 0xd7, 0x6c,
	0x92, 0xa3, 0xc7, 0xe5, 0x87, 0xaa, 0x91, 0xd7, 0xbe, 0x90, 0x2b, 0x6a, 0xd5, 0x67, 0xab, 0x1d,
	0xa3, 0x5d, 0xa6, 0xf7, 0xaa, 0xd4, 0xfd, 0xba, 0x20, 0xed, 0x4a, 0xb5, 0xf7, 0xbd, 0xc5, 0x38,
	0xb8, 0xde, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x51, 0x86, 0x3f, 0x9d, 0x78, 0x01, 0x00, 0x00,
}
