// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather/weather.proto

package weather

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCurrentWeatherRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentWeatherRequest) Reset()         { *m = GetCurrentWeatherRequest{} }
func (m *GetCurrentWeatherRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentWeatherRequest) ProtoMessage()    {}
func (*GetCurrentWeatherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_470277fee9d6b73e, []int{0}
}

func (m *GetCurrentWeatherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentWeatherRequest.Unmarshal(m, b)
}
func (m *GetCurrentWeatherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentWeatherRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrentWeatherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentWeatherRequest.Merge(m, src)
}
func (m *GetCurrentWeatherRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentWeatherRequest.Size(m)
}
func (m *GetCurrentWeatherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentWeatherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentWeatherRequest proto.InternalMessageInfo

func (m *GetCurrentWeatherRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetCurrentWeatherReply struct {
	TempFahrenheit       int32    `protobuf:"varint,1,opt,name=tempFahrenheit,proto3" json:"tempFahrenheit,omitempty"`
	PrecipitationPct     int32    `protobuf:"varint,2,opt,name=precipitationPct,proto3" json:"precipitationPct,omitempty"`
	HumidityPct          int32    `protobuf:"varint,3,opt,name=humidityPct,proto3" json:"humidityPct,omitempty"`
	WindMPH              int32    `protobuf:"varint,4,opt,name=windMPH,proto3" json:"windMPH,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentWeatherReply) Reset()         { *m = GetCurrentWeatherReply{} }
func (m *GetCurrentWeatherReply) String() string { return proto.CompactTextString(m) }
func (*GetCurrentWeatherReply) ProtoMessage()    {}
func (*GetCurrentWeatherReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_470277fee9d6b73e, []int{1}
}

func (m *GetCurrentWeatherReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentWeatherReply.Unmarshal(m, b)
}
func (m *GetCurrentWeatherReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentWeatherReply.Marshal(b, m, deterministic)
}
func (m *GetCurrentWeatherReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentWeatherReply.Merge(m, src)
}
func (m *GetCurrentWeatherReply) XXX_Size() int {
	return xxx_messageInfo_GetCurrentWeatherReply.Size(m)
}
func (m *GetCurrentWeatherReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentWeatherReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentWeatherReply proto.InternalMessageInfo

func (m *GetCurrentWeatherReply) GetTempFahrenheit() int32 {
	if m != nil {
		return m.TempFahrenheit
	}
	return 0
}

func (m *GetCurrentWeatherReply) GetPrecipitationPct() int32 {
	if m != nil {
		return m.PrecipitationPct
	}
	return 0
}

func (m *GetCurrentWeatherReply) GetHumidityPct() int32 {
	if m != nil {
		return m.HumidityPct
	}
	return 0
}

func (m *GetCurrentWeatherReply) GetWindMPH() int32 {
	if m != nil {
		return m.WindMPH
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCurrentWeatherRequest)(nil), "weather.GetCurrentWeatherRequest")
	proto.RegisterType((*GetCurrentWeatherReply)(nil), "weather.GetCurrentWeatherReply")
}

func init() {
	proto.RegisterFile("weather/weather.proto", fileDescriptor_470277fee9d6b73e)
}

var fileDescriptor_470277fee9d6b73e = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0xad, 0x5f, 0xc5, 0x08, 0xa2, 0x01, 0x25, 0x78, 0x71, 0xed, 0x41, 0xc4, 0x43, 0xc3,
	0xae, 0x82, 0x77, 0x05, 0xf5, 0x22, 0x2c, 0xbd, 0x88, 0xde, 0xd2, 0x66, 0x30, 0x91, 0x6d, 0x12,
	0xa7, 0x53, 0x96, 0xfe, 0x23, 0x7f, 0xa6, 0x6c, 0x6c, 0x41, 0x76, 0x75, 0x4f, 0xe1, 0x7d, 0xf2,
	0x0c, 0xbc, 0xcc, 0xb0, 0xe3, 0x39, 0x28, 0x32, 0x80, 0xb2, 0x7f, 0xf3, 0x80, 0x9e, 0x3c, 0x4f,
	0xfb, 0x98, 0xdd, 0x30, 0xf1, 0x08, 0x74, 0xdf, 0x22, 0x82, 0xa3, 0x97, 0x1f, 0x58, 0xc0, 0x67,
	0x0b, 0x0d, 0x71, 0xc1, 0x52, 0xa5, 0x35, 0x42, 0xd3, 0x88, 0x64, 0x94, 0x5c, 0xee, 0x15, 0x43,
	0xcc, 0xbe, 0x12, 0x76, 0xf2, 0xc7, 0x58, 0x98, 0x75, 0xfc, 0x82, 0x1d, 0x10, 0xd4, 0xe1, 0x41,
	0x19, 0x04, 0x67, 0xc0, 0x52, 0x9c, 0xdd, 0x29, 0x96, 0x28, 0xbf, 0x62, 0x87, 0x01, 0xa1, 0xb2,
	0xc1, 0x92, 0x22, 0xeb, 0xdd, 0xb4, 0x22, 0xb1, 0x19, 0xcd, 0x15, 0xce, 0x47, 0x6c, 0xdf, 0xb4,
	0xb5, 0xd5, 0x96, 0xba, 0x85, 0xb6, 0x15, 0xb5, 0xdf, 0x68, 0x51, 0x75, 0x6e, 0x9d, 0x7e, 0x9e,
	0x3e, 0x89, 0xed, 0xf8, 0x3b, 0xc4, 0x89, 0x66, 0x69, 0xdf, 0x8f, 0xbf, 0xb2, 0xa3, 0x95, 0xd2,
	0xfc, 0x3c, 0x1f, 0x36, 0xf3, 0xdf, 0x1e, 0x4e, 0xcf, 0xd6, 0x29, 0x61, 0xd6, 0x65, 0x1b, 0x77,
	0xe3, 0x37, 0xf9, 0x6e, 0xc9, 0xb4, 0x65, 0x5e, 0xf9, 0x5a, 0x7e, 0xd4, 0x0a, 0xc9, 0xba, 0xf1,
	0xe4, 0x56, 0x6a, 0xd5, 0x98, 0xd2, 0x2b, 0xd4, 0x72, 0xe9, 0x10, 0xe5, 0x6e, 0xbc, 0xc4, 0xf5,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x6f, 0xf5, 0xd8, 0xa2, 0x01, 0x00, 0x00,
}
